### ISSUE TITLE
timeless-0.8.0.2 doesn't compile with GHC 7.10.x

### ISSUE THREAD

**Issue by peti** [carldong/timeless#1]
Citing from http://hydra.cryp.to/build/1337291/log/raw:

```
Preprocessing library timeless-0.8.0.2...
src/FRP/Timeless/Tutorial.lhs line 1: unlit: Program line next to comment
src/FRP/Timeless/Tutorial.lhs line 3: unlit: Program line next to comment
```

**Comment by rongcuid** [comment]
Does it work from the repository now?

**Comment by carldong** [comment]
Also, try to build it using stack

**Comment by peti** [comment]
It's not easy for me to test that -- our CI infrastructure will build the new version automatically once it's released on Hackage, but it doesn't build things from Github.

**Comment by rongcuid** [comment]
It build on my machine now. However, I cannot release another version until I complete Tutorial 2 and console framework, sorry. It might be today or tomorrow

**Comment by rongcuid** [comment]
New version uploaded

**Comment by peti** [comment]
Build failure is fixed http://hydra.cryp.to/job/nixpkgs/haskell-updates/haskellPackages.timeless.x86_64-linux.
